<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/12/14 09:48:52
sfConfig::add(array(
  'mod_alerta_visitante_enabled' => true,
  'mod_alerta_visitante_view_class' => 'sfPHP',
));
