<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/12/13 14:34:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=192.168.49.49;dbname=siglas-local',
  'username' => 'postgres',
  'password' => 123456,
  'name' => 'doctrine',
)),);
