<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/12/13 14:33:44
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
